### ISSUE TITLE
Comments in tslint.json

### ISSUE THREAD

**Issue by enoshixi** [wbuchwalter/tslint-loader#31]
Comments in tslint.json no longer work as of version 2.1.5.

```
Module build failed: SyntaxError: Unexpected token /
    at Object.parse (native)
    at loadConfigurationFromPath (node_modules\tslint\lib\configuration.js:81:21)
    at Object.findConfiguration (node_modules\tslint\lib\configuration.js:39:12)
    at Object.loadRelativeConfig (node_modules\tslint-loader\index.js:22:34)
    at Object.module.exports (node_modules\tslint-loader\index.js:102:35)
 @ multi app
```

It worked fine in version 2.1.4.

**Comment by blacksonic** [comment]
@enoshixi  Is it still an issue?

**Comment by enoshixi** [comment]
Working now using `tslint@4.01` and `tslint-loader@3.0.0`.
