### ISSUE TITLE
fails if you lack module.exports.tslint.configuration (if you put your tslint config in a separate file)

### ISSUE THREAD

**Issue by wcarmon** [wbuchwalter/tslint-loader#57]
this fails with tslint 3.15.x and tslint 4.0.x

# on 4.0.x
Module build failed: TypeError: Cannot read property 'findConfiguration' of undefined
    at resolveOptions (.../node_modules/tslint-loader/index.js:28:63)

# on 3.15.x
Module build failed: TypeError: Cannot read property 'findConfiguration' of undefined
    at resolveOptions (.../node_modules/tslint-loader/index.js:26:63)

**Comment by vlio20** [comment]
@piq9117, @wcarmon - were you able to solve this issue? I am using webpack2 rc3

**Comment by afnpires** [comment]
By updating to versions 4.3.1 of tslint and 3.3.0 of tslint-loader the error ceases to exist.

**Comment by whisher** [comment]
Hi there,
same issue here (4.3.1 of tslint and 3.3.0 of tslint-loader)

ERROR in ./src/polyfills.ts
Module build failed: Error
    at new FatalError (/Users/webpack/angular2-webpack2-starter/node_modules/tslint/lib/error.js:33:23)
    at Function.findConfiguration (/Users/webpack/angular2-webpack2-starter/node_modules/tslint/lib/configuration.js:97:15)
    at resolveOptions (/Users/webpack/angular2-webpack2-starter/node_modules/tslint-loader/index.js:26:64)
    at Object.module.exports (/Users/webpack/angular2-webpack2-starter/node_modules/tslint-loader/index.js:110:17)
 @ multi (webpack)-dev-server/client?http://localhost:7000 ./src/polyfills.ts

**Comment by blacksonic** [comment]
It needs Tslint 4.0+ and there is also a test case for no tslint configuration, does it still exist?

**Comment by blacksonic** [comment]
Added explicit check for Tslint version in code and documentation.

**Comment by ollwenjones** [comment]
running into something similar, but only if I'm consuming typescript from within `node_modules` (in my case, peer scoped packages, npm linked together.)

**Comment by blacksonic** [comment]
@wcarmon can you provide an example repository?

**Comment by wcarmon** [comment]
We gave up on that approach and just run linting directly to avoid any of
these issues.
