### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by akashbiz** [wbuchwalter/tslint-loader#81]
Hello, Facing this issue while setting up a new copy of repo [Angular2-Ionic2-Webpack-Master](https://github.com/strictd/angular2-ionic2-webpack)

Facing:

> Uncaught Error: Module build failed: Error
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
    at eval (eval at 36 (http://localhost:8080/js/vendor.js:6:1), <anonymous>:1:7)
    at Object.36 (http://localhost:8080/js/vendor.js:6:1)
    at __webpack_require__ (http://localhost:8080/js/polyfills.js:55:30)
    at Object.81 (http://localhost:8080/js/vendor.js:14:18)
    at __webpack_require__ (http://localhost:8080/js/polyfills.js:55:30)
    at webpackJsonpCallback (http://localhost:8080/js/polyfills.js:26:23)
    at http://localhost:8080/js/vendor.js:1:1
(anonymous) @ VM4383:1
36 @ vendor.js:6
__webpack_require__ @ polyfills.js:55
81 @ vendor.js:14
__webpack_require__ @ polyfills.js:55
webpackJsonpCallback @ polyfills.js:26
(anonymous) @ vendor.js:1

> Uncaught Error: Module build failed: Error
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
    at eval (eval at 34 (http://localhost:8080/js/app.js:6:1), <anonymous>:1:7)
    at Object.34 (http://localhost:8080/js/app.js:6:1)
    at __webpack_require__ (http://localhost:8080/js/polyfills.js:55:30)
    at Object.79 (http://localhost:8080/js/app.js:14:18)
    at __webpack_require__ (http://localhost:8080/js/polyfills.js:55:30)
    at webpackJsonpCallback (http://localhost:8080/js/polyfills.js:26:23)
    at http://localhost:8080/js/app.js:1:1
(anonymous) @ VM4385:1
34 @ app.js:6
__webpack_require__ @ polyfills.js:55
79 @ app.js:14
__webpack_require__ @ polyfills.js:55
webpackJsonpCallback @ polyfills.js:26
(anonymous) @ app.js:1
client?8505:38 [WDS] Errors while compiling.
client?8505:80 ./src/browser/app/polyfills.ts

> Module build failed: Error
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/browser/app/polyfills.ts
errors @ client?8505:80
sock.onmessage @ socket.js?e5d0:37
EventTarget.dispatchEvent @ eventtarget.js?3e89:51
(anonymous) @ main.js?45b8:274
SockJS._transportMessage @ main.js?45b8:272
EventEmitter.emit @ emitter.js?927b:50
WebSocketTransport.ws.onmessage @ websocket.js?c17e:35
client?8505:80 ./src/browser/app/vendor.ts

> Module build failed: Error
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/browser/app/vendor.ts
errors @ client?8505:80
sock.onmessage @ socket.js?e5d0:37
EventTarget.dispatchEvent @ eventtarget.js?3e89:51
(anonymous) @ main.js?45b8:274
SockJS._transportMessage @ main.js?45b8:272
EventEmitter.emit @ emitter.js?927b:50
WebSocketTransport.ws.onmessage @ websocket.js?c17e:35
client?8505:80 ./src/browser/app/main.ts

**Comment by t-p-l-k** [comment]
Related issue: https://github.com/wbuchwalter/tslint-loader/issues/57
